### PR TITLE
Make the recipe noarch

### LINKED ISSUE #42: Move to noarch: python?
### Comment:

As we only build for python 3.7+ now, the only remaining relevant python-version-specific thing is an [un-pinned  `typing_extensions`](https://github.com/agronholm/anyio/blob/3.6.0/setup.cfg#L36). It looks like stdlib is always [preferred](https://github.com/agronholm/anyio/search?q=typing_extensions). 

There is probably no harm in at least trying it out on a PR to reduce the number of builds we have to do.

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #42

### CODE REVIEW

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by martinRenou** [comment]
Friendly ping @bollwyvl 😄

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Thanks!

**Pull request merged**
